### ISSUE TITLE
Incorrect command or typo ?

### ISSUE THREAD

**Issue by FRashkar-pm** [PandaOaseBE/MobsLite#2]
Are op players able to use this command, or is it specially made for players who have permission from this command?
If the op player can use it, maybe this can help
- Change this :
```yaml
permissions:
  kill.mobslite:
    description: "/kill"
    default: false
  summon.mobslite:
    description: "/summon"
    default: false
  list.mobslite:
    description: "/mobslist"
    default: false
```
- To this :
```yaml
permissions:
  kill.mobslite:
    description: "/mkill"
    default: op
  summon.mobslite:
    description: "/msummon"
    default: op
  list.mobslite:
    description: "/mmobslist"
    default: op
```
According to this :
```php
parent::__construct("mkill", "§bMobsLite §8» §7Kill all Entitys");
parent::__construct("mlist", "§bMobsLite §8» §7List all Mobs that can spawn");
parent::__construct("msummon", "§bMobsLite §8» §7Summon Mob Command");
```

**Comment by pandaa-be** [comment]
I use the permissionsystem implemented in pocketmine, I don´t use op  on my own server..

```
"permissions:
  exampleperm.command.example:
    description: "Allows the user to run the example command"
    # Default state of the permission. Explanation of each value:
    # op: only op players have this permission by default
    # true: everyone has this permission by default
    # false: no one has this permission by default
    default: true"
```
    
    I edited the description, thy :))
